name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  GO_PRIVATE: "github.com/acquirecloud/*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        run: go test -v -cover ./...
